In [1]:
import pandas as pd

In [5]:
df = pd.read_csv('BTCUSDT_5min_from_2019.csv')
df['timestamp'] = pd.to_datetime(df['timestamp'])  # 把 timestamp 轉為 datetime 格式
df.set_index('timestamp', inplace=True) 


# 每小時 00 分 open 價格（也作為 hour_k_open）
df["hour_00_open"] = df[df.index.minute == 0]["open"]
df["hour_k_open"] = df["hour_00_open"]

# 每小時 45 分 open 價格
df["hour_45_open"] = df[df.index.minute == 45]["open"]

# 每小時 55 分 close 價格（作為 hour_k_close）
df["hour_k_close"] = df[df.index.minute == 55]["close"]

#過濾掉前後沒有開收的資料，沒有完整一小時的資料。
# 3. 篩選完整區段
df_filtered = df.loc['2020-01-01 18:00:00':'2025-06-29 12:55:00'].copy()

In [7]:
df_filtered.head(25)

,open,high,low,close,hour_00_open,hour_k_open,hour_45_open,hour_k_close
timestamp,,,,,,,,
2020-01-01 18:00:00,7233.87,7235.91,7228.88,7228.88,7233.87,7233.87,NaN,NaN
2020-01-01 18:05:00,7229.21,7237.00,7229.21,7236.99,NaN,NaN,NaN,NaN
2020-01-01 18:10:00,7236.99,7240.00,7233.98,7239.69,NaN,NaN,NaN,NaN
2020-01-01 18:15:00,7239.69,7241.95,7236.03,7237.03,NaN,NaN,NaN,NaN
2020-01-01 18:20:00,7236.38,7238.44,7235.15,7237.03,NaN,NaN,NaN,NaN
2020-01-01 18:25:00,7237.48,7238.01,7233.01,7233.01,NaN,NaN,NaN,NaN
2020-01-01 18:30:00,7233.00,7233.00,7222.00,7227.27,NaN,NaN,NaN,NaN
2020-01-01 18:35:00,7226.97,7229.19,7222.00,7224.90,NaN,NaN,NaN,NaN
2020-01-01 18:40:00,7225.13,7231.79,7225.13,7230.73,NaN,NaN,NaN,NaN
2020-01-01 18:45:00,7230.73,7233.00,7226.12,7229.88,NaN,NaN,7230.73,NaN
2020-01-01 18:50:00,7229.71,7231.76,7229.30,7231.19,NaN,NaN,NaN,NaN
2020-01-01 18:55:00,7231.29,7239.57,7231.27,7237.47,NaN,NaN,NaN,7237.47
2020-01-01 19:00:00,7237.83,7237.83,7232.00,7235.50,7237.83,7237.83,NaN,NaN
2020-01-01 19:05:00,7235.49,7235.50,7228.99,7230.47,NaN,NaN,NaN,NaN
2020-01-01 19:10:00,7230.29,7230.29,7224.00,7229.89,NaN,NaN,NaN,NaN
2020-01-01 19:15:00,7229.99,7232.50,7229.98,7232.11,NaN,NaN,NaN,NaN
2020-01-01 19:20:00,7232.12,7232.12,7224.01,7224.49,NaN,NaN,NaN,NaN
2020-01-01 19:25:00,7224.49,7229.00,7223.15,7225.16,NaN,NaN,NaN,NaN
2020-01-01 19:30:00,7225.00,7230.99,7225.00,7230.47,NaN,NaN,NaN,NaN
2020-01-01 19:35:00,7230.64,7233.00,7227.88,7227.88,NaN,NaN,NaN,NaN
2020-01-01 19:40:00,7227.45,7232.18,7224.04,7224.99,NaN,NaN,NaN,NaN
2020-01-01 19:45:00,7225.50,7228.68,7223.94,7228.68,NaN,NaN,7225.50,NaN
2020-01-01 19:50:00,7228.02,7228.91,7227.58,7228.22,NaN,NaN,NaN,NaN
2020-01-01 19:55:00,7228.66,7228.66,7224.00,7226.35,NaN,NaN,NaN,7226.35
2020-01-01 20:00:00,7226.56,7233.77,7226.56,7230.00,7226.56,7226.56,NaN,NaN

In [27]:
# 4. forward-fill 補值（每小時最多 12 根 5 分鐘 K 線）
df_filtered["hour_00_open"] = df_filtered["hour_00_open"].ffill(limit=11)
df_filtered["hour_k_open"] = df_filtered["hour_k_open"].ffill(limit=11)
df_filtered["hour_45_open"] = df_filtered["hour_45_open"].ffill(limit=11)
df_filtered["hour_k_close"] = df_filtered["hour_k_close"].ffill(limit=11)

In [28]:
# 5. 僅保留每小時的最後一根（55分）
df_hourly = df_filtered[df_filtered.index.minute == 55].copy()

# 6. 條件判斷與機率計算
cond_up = (df_hourly["hour_45_open"] - df_hourly["hour_00_open"] > 0) & (df_hourly["hour_k_close"] > df_hourly["hour_k_open"])
cond_down = (df_hourly["hour_45_open"] - df_hourly["hour_00_open"] < 0) & (df_hourly["hour_k_close"] < df_hourly["hour_k_open"])
total = len(df_hourly)
success_count = (cond_up | cond_down).sum()
probability = success_count / total

# 7. 輸出結果
print(f"條件成立次數: {success_count}")
print(f"總次數: {total}")
print(f"機率: {probability:.4%}")

條件成立次數: 40239
總次數: 48139
機率: 83.5892%

# 凱莉公式

In [41]:
def kelly_criterion(p, b):
    """
    凱莉公式：計算最佳下注比例
    :param p: 贏的機率，例如 0.55
    :param b: 賠率（下注 1 元可賺 b 元）
    :return: 最佳下注比例（例如 0.1 表示下注 10%）
    """
    f = (p * (b + 1) - 1) / b
    return max(f, 0)  # 若 f 為負，表示不應下注

def expected_value(p, b):
    """
    計算期望值（每下注 1 元的預期報酬）
    :param p: 勝率 (例如 0.55)
    :param b: 賠率（下注 1 元贏回 b 元）
    :return: 每注 1 元的期望值
    """
    return p * b - (1 - p)

In [52]:
# 範例：贏的機率 55%，賠率為 1（等於賠 1 拿 2）
p = probability
option = 0.8
b = (1-option)/option

optimal_fraction = kelly_criterion(p, b)
print(f"最佳下注比例為：{optimal_fraction:.2%}")

ev = expected_value(p, b)
print(f"期望值為: {ev}")
print(p, b)

最佳下注比例為：17.95%
期望值為: 0.04486487047923718
0.8358918963833898 0.24999999999999994